load("@rules_java//java:java_binary.bzl", "java_binary")
load("//combine:properties.bzl", "combine_version")
load("//rule:class_version_test.bzl", "class_version_test")
load("//rule:merge_library.bzl", "kt_merge_library", "merge_library_jar")
load("//rule/neoforge:merge_jij.bzl", "neoforge_merge_jij")
load("//rule/neoforge:mod_toml_jar.bzl", "neoforge_mod_toml_jar")
load("//touchcontroller:libraries.bzl", "touchcontroller_neoforge_libraries")
load("//touchcontroller:properties.bzl", "touchcontroller_api_version", "touchcontroller_authors", "touchcontroller_contributors", "touchcontroller_description", "touchcontroller_homepage", "touchcontroller_issue_tracker", "touchcontroller_license", "touchcontroller_source", "touchcontroller_version")

neoforge_mod_toml_jar(
    name = "neoforge_mod_toml",
    src = "resources/neoforge.mods.toml",
    substitutions = {
        "${version}": touchcontroller_version,
        "${license}": touchcontroller_license,
        "${home_page}": touchcontroller_homepage,
        "${sources_page}": touchcontroller_source,
        "${issue_tracker}": touchcontroller_issue_tracker,
        "${description}": touchcontroller_description,
        "${combine_version}": combine_version,
        "${mod_authors}": ", ".join(touchcontroller_authors),
        "${mod_contributors}": ", ".join(touchcontroller_contributors),
    },
)

kt_merge_library(
    name = "neoforge_unmerged",
    srcs = glob(
        include = [
            "**/*.kt",
            "**/*.java",
        ],
    ),
    javac_opts = "//touchcontroller:javac_opts_jvm_25",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_25",
    merge_deps = [
        "//touchcontroller/versions/neoforge/gal/key/26.2",
    ],
    merge_only_deps = [
        "//touchcontroller/versions/neoforge/gal/26.2",
    ],
    resource_jars = [
        ":neoforge_mod_toml",
        "//touchcontroller/resources/texture:icon_jar",
    ],
    resource_strip_prefix = "touchcontroller/versions/neoforge/26.2/resources",
    resources = glob(
        include = ["resources/**"],
        exclude = ["resources/neoforge.mods.toml"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//game/26.2:game_client_libraries",
        "//game/26.2:game_client_neoforge",
        # Classpath separator
        "//combine/backend/minecraft/render/26.2",
        "//touchcontroller/buildinfo",
        "//touchcontroller/common/config",
        "//touchcontroller/common/config/data",
        "//touchcontroller/common/config/holder",
        "//touchcontroller/common/event/block",
        "//touchcontroller/common/event/connection",
        "//touchcontroller/common/event/key",
        "//touchcontroller/common/event/render",
        "//touchcontroller/common/event/tick",
        "//touchcontroller/common/event/window",
        "//touchcontroller/common/gal/key",
        "//touchcontroller/common/layout/data",
        "//touchcontroller/common/model",
        "//touchcontroller/common/platform/provider",
        "//touchcontroller/common/ui/config/screen",
        "//touchcontroller/versions/extension/26.2",
        "//touchcontroller/versions/gal/gameconfig/26.2",
        "//touchcontroller/versions/gal/key/26.2",
        "@neoforge_26_2//:io_github_llamalad7_mixinextras_neoforge",
        "@neoforge_26_2//:net_fabricmc_sponge_mixin",
        "@neoforge_26_2//:net_neoforged_bus",
        "@neoforge_26_2//:net_neoforged_fancymodloader_loader",
        "@neoforge_26_2//:net_neoforged_mergetool",
    ],
)

merge_library_jar(
    name = "neoforge",
    aspect_impl_package_suffix = "neoforge.v26_2",
    aspects = ["//touchcontroller/versions/26.2:26.2_merged"],
    deps = [":neoforge_unmerged"],
)

class_version_test(
    name = "neoforge_class_version",
    class_major = 69,
    jars = [":neoforge"],
    tags = ["class_version"],
)

alias(
    name = "26.2",
    actual = "neoforge",
    visibility = ["//touchcontroller:__subpackages__"],
)

neoforge_merge_jij(
    name = "neoforge_merged",
    input = ":neoforge",
    deps = touchcontroller_neoforge_libraries | {
        "//combine/theme/blackstone:blackstone_common": "top.fifthlight.combine:combine-theme-blackstone:%s:" % combine_version,
        "//combine/theme/blackstone:blackstone_vanilla": "top.fifthlight.combine:combine-theme-blackstone-vanilla:%s:" % combine_version,
        "//touchcontroller/resources/lang": "top.fifthlight.touchcontroller:touchcontroller-lang-modern:%s:" % touchcontroller_version,
        "//touchcontroller/resources/texture:texture_common": "top.fifthlight.touchcontroller:touchcontroller-texture:%s:" % touchcontroller_version,
        "//touchcontroller/resources/texture:texture_vanilla": "top.fifthlight.touchcontroller:touchcontroller-texture-vanilla:%s:" % touchcontroller_version,
        "//touchcontroller/api": "top.fifthlight.touchcontroller:api:%s:" % touchcontroller_api_version,
        "//touchcontroller/common:common_merged": "top.fifthlight.touchcontroller:neoforge:%s:" % touchcontroller_version,
        "//touchcontroller/versions/26.2:26.2_merged": "top.fifthlight.touchcontroller:neoforge-26-2:%s:" % touchcontroller_version,
    },
)

java_binary(
    name = "dev_client",
    srcs = [],
    data = [
        "//game/26.2:game_client_assets",
        "//game/26.2:game_client_assets_version",
    ],
    env = {
        "LANG": "en_US.UTF8",
    },
    jvm_flags = [
        "-Ddev.launch.version=26.2",
        "-Ddev.launch.neoFormVersion=26.2-1",
        "-Ddev.launch.type=client",
        "-Ddev.launch.assetsVersion=$(rlocationpath //game/26.2:game_client_assets_version)",
        "-Ddev.launch.mainClass=net.neoforged.fml.startup.Client",
        "-Xmx4G",
        "--add-opens=java.base/java.lang.invoke=ALL-UNNAMED",
        "--add-exports=jdk.naming.dns/com.sun.jndi.dns=java.naming",
    ] + select({
        "@platforms//os:macos": ["-XstartOnFirstThread"],
        "//conditions:default": [],
    }),
    main_class = "top.fifthlight.fabazel.devlaunchwrapper.DevLaunchWrapper",
    runtime_deps = [
        "//game/26.2:game_client_neoforge",
        "//game/26.2:game_client_libraries",
        "//game/26.2:game_kotlinforforge",
        "//blazesdl/26.2",
        # Classpath separator
        ":neoforge_merged",
        "//rule/dev_launch_wrapper",
        "@neoforge_26_2//:neoforge_deps",
        "//combine/backend/minecraft:minecraft_common_standalone",
        "//combine/backend/minecraft:combine_neoforge_libraries",
        "//combine/backend/minecraft/versions/26.2:26.2_merged",
        "@maven//:org_jetbrains_kotlin_kotlin_reflect",
    ],
)
