load("//rule:merge_library.bzl", "kt_merge_library")

kt_merge_library(
    name = "model",
    srcs = glob(["*.kt"]),
    javac_opts = "//touchcontroller:javac_opts_jvm_8",
    kotlinc_opts = "//touchcontroller:kotlinc_opts_jvm_8",
    merge_deps = [
        "//touchcontroller/buildinfo",
        "//touchcontroller/common/config",
        "//touchcontroller/common/config/holder",
        "//touchcontroller/common/ui/config/state",
        "//touchcontroller/common/ui/model",
    ],
    visibility = ["//touchcontroller:__subpackages__"],
    deps = [
        "@maven//:androidx_compose_runtime_runtime_desktop",
        "@maven//:cafe_adriel_voyager_voyager_screenmodel_desktop",
        "@maven//:org_jetbrains_kotlinx_kotlinx_coroutines_core_jvm",
    ],
)
